config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :departments do
    resources :courses
  end
  root :to => 'departments#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :department
  validates :name, presence: true
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :courses, dependent: :destroy
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
 before_filter :authenticate_user!
  def new
    @department = Department.find(params[:department_id])
    @course = @department.courses.build
  end
  
  def show
    
  end

  def edit
    @course = Course.find(params[:id])
  end

  def index
    @department = Department.find(params[:department_id])
    @courses = Course.where(department_id: params[:department_id])
  end
  
  def update
    @course = Course.find params[:id]
    @course.update_attributes!(course_params)
    department = @course.department
    redirect_to department_courses_path(department)
  end

  def create
     @department = Department.find(params[:department_id])
     @course = @department.courses.create(course_params)
     redirect_to department_courses_path
  end
  private 
  def course_params
    params.require(:course).permit(:code, :name, :professor)
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @departments = Department.all
  end

  def create
    @department = Department.create(department_params)
    redirect_to departments_path
  end
  

  def update
    @department = Department.find params[:id]
    @department.update_attributes!(department_params)
    redirect_to department_path(@department)
  end

  def edit
    @department = Department.find params[:id]
  end
  def show
    id = params[:id]
    @department= Department.find(id)
  end
  private
  def department_params
      params.require(:department).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/courses/create.html.erb
<h1>Courses#create</h1>
<p>Find me in app/views/courses/create.html.erb</p>

app/views/courses/edit.html.haml
%h1 Courses#edit
%p Find me in app/views/courses/edit.html.haml
%h2 Editing Course
= form_tag department_course_path(course_id: @course.id), :method => :put do
  = label :course, :code, 'Code'
  = text_field :course, :code
  = label :course, :name, 'Name'
  = text_field :course, :name
  = label :course, :professor, 'Professor'
  = text_field :course, :professor
  = submit_tag 'Save changes'

app/views/courses/index.html.haml
%h1 Courses#index
%p="Courses from " + @department.name + " department" 
%table#courses
  %thead
    %tr
      %th code
      %th name
      %th professor
      %th more actions
    %tbody
      - @courses.each do |course|
        %tr
          %td= course.code
          %td= course.name
          %td= course.professor
          %td= link_to "Edit course information", edit_department_course_path(course.department, course)
=link_to 'Add new course', new_department_course_path(@department)

app/views/courses/new.html.haml
%h1 Courses#new
%p 
="Adding a new course to " + @department.name + " department" 
%h2 Create a new Course
= form_tag department_courses_path(@department), :method => :post do
  = label :course, :code, 'Code'
  = text_field :course, :code
  = label :course, :name, 'Name'
  = text_field :course, :name
  = label :course, :professor, 'Professor'
  = text_field :course, :professor
  = submit_tag 'Save changes'

app/views/courses/show.html.erb
<h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p>

app/views/courses/update.html.erb
<h1>Courses#update</h1>
<p>Find me in app/views/courses/update.html.erb</p>

app/views/departments/create.html.erb
<h1>Departments#create</h1>
<p>Find me in app/views/departments/create.html.erb</p>

app/views/departments/edit.html.haml
%h1 Departments#edit
%h2 Edit Department information
%p Find me in app/views/departments/edit.html.haml
= form_tag department_path(@department), :method => :put do
  = label :department, :name, 'Name'
  = text_field :department, :name
  = label :department, :description, 'Description'
  = text_field :department, :description
  = submit_tag 'Save changes'

app/views/departments/index.html.haml
%%h1 All Departments
%table#departments
  %thead
    %tr
      %th Name
      %th Description
      %th More Info
      %th courses
    %tbody
      - @departments.each do |d|
        %tr
          %td= d.name
          %td= d.description
          %td= link_to "More about #{d.name}", department_path(d)
          %td= link_to "View courses", department_courses_path(d)
=link_to 'Add new Department', new_department_path

app/views/departments/new.html.haml
h1 Departments#new
%p Find me in app/views/departments/new.html.haml
%h2 Create a new Department
= form_tag departments_path, :method => :post do
  = label :department, :name, 'Name'
  = text_field :department, :name
  = label :department , :description, 'Description' 
  = text_field :department, :description
  = submit_tag 'Save changes'

app/views/departments/show.html.haml
%h2 Details about #{@department.name}
%ul#details
  %li
    description:
    = @department.description
  
=link_to 'Edit department information', edit_department_path(@department)
=link_to 'Back to departments list', departments_path

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dc" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Dc" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>